config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'pages#decide'

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  get 'my_reviews', to: 'review#my_reviews'

  scope 'books', controller: :book do
    scope '/:book_id' do
      resources :reviews, controller: :review, param: :review_id
      resources :discussions, controller: :discussion, param: :discussion_id do
        resources :replies, controller: :reply, param: :reply_id, except: %i[index create update]
      end
      get 'view'
    end

    get 'search'
    get '/:book_id', to: 'book#view'
  end

  get 'search_books', to: 'book#search'
  get 'home', to: 'pages#home'

  resource :replies, controller: :reply, only: %i[create], path: '/books/:book_id/discussions/:discussion_discussion_id/replies',
                     as: 'replies'
  resource :replies, controller: :reply, only: %i[update], path: '/books/:book_id/discussions/:discussion_discussion_id/replies/:reply_id',
                     as: 'reply'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/reply.rb
# frozen_string_literal: true

class Reply < ApplicationRecord
  belongs_to :discussion
  belongs_to :author, class_name: 'User', foreign_key: :author_id

  validates :content, presence: true, length: { minimum: 0, maxmium: 1000 }
end

app/controllers/reply_controller.rb
# frozen_string_literal: true

# ReplyController
class ReplyController < ApplicationController
  before_action :find_reply, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[show]
  before_action :correct_user, only: %i[edit update destroy]

  def show
    @title = 'View Reply'
  end

  def new
    @reply = Reply.new
    @title = 'New Reply'
    @book_name = (HTTP.get("https://www.googleapis.com/books/v1/volumes/#{params[:book_id]}").parse)['volumeInfo']['title']
  end

  def edit
    @book_name = (HTTP.get("https://www.googleapis.com/books/v1/volumes/#{params[:book_id]}").parse)['volumeInfo']['title']
  end

  def create
    @reply = Reply.new(reply_params)
    @reply.discussion_id = params[:discussion_discussion_id]
    @reply.author_id = current_user.id

    if @reply.save
      flash[:notice] = 'Reply was successfully created.'
      redirect_to discussion_reply_path(book_id: params[:book_id], discussion_discussion_id: @reply.discussion_id,
                             reply_id: @reply.id)
    else
      flash[:alert] = 'Failed to create reply.'
      redirect_to request.referrer
    end
  end

  def update
    if @reply.update(reply_params)
      flash[:notice] = 'Reply was successfully updated.'
      redirect_to discussion_reply_path(book_id: params[:book_id], discussion_discussion_id: @reply.discussion_id,
                             reply_id: @reply.id)
    else
      flash[:alert] = 'Failed to update reply.'
      redirect_to request.referrer
    end
  end

  def destroy
    @reply.destroy
    flash[:notice] = 'Reply deleted successfully.'

    redirect_to view_path(book_id: @reply.discussion.gbook_id)
  end

  private

  def find_reply
    @reply = Reply.find(params[:reply_id])
  end

  def correct_user
    @reply = current_user.replies.find(params[:reply_id])
    redirect_to discussion_reply_path, notice: 'Not authorized to edit this reply.' if @reply.nil?
  end

  def reply_params
    params.require(:reply).permit(:content)
  end
end

app/helpers/reply_helper.rb
module ReplyHelper
end

app/views/reply/_form.html.erb
<%= form_with model: @reply do |f| %>
  <div class="mb-3">
    <%= f.label :content, class: "form-label" %>
    <%= f.text_area :content, autocomplete: "content", class: "form-control", required: true, maxlength: 1000 %>
  </div>
  <div class="mb-3">
    <%= f.submit "Submit Reply", class: "btn btn-primary"%>
  </div>
<% end %>

app/views/reply/edit.html.erb
<div class="container mt-5">
  <div class="content-section">
    <h2>Edit Reply</h2>
    <h4 class="text-muted">Book: <%= @book_name %></h4>
    <%= render "form" %>
  </div>
</div>

app/views/reply/new.html.erb
<div class="container mt-5">
  <div class="content-section">
    <h2>New Reply</h2>
    <h4 class="text-muted">Book: <%= @book_name %></h4>
    <%= render "form" %>
  </div>
</div>

app/views/reply/show.html.erb
<div class= "container mt-5">
  <div class="card mb-3">
    <div class="card-body">
      <h5 class="card-subtitle mb-3 text-muted">
        <b>Written by:</b> <%= @reply.author.username %></br>
        <b>Written on:</b> <%= @reply.created_at.strftime("%B %d, %Y at %-I:%M %p") %> 
      </h5>
      <p class="card-text">
      <%= @reply.content %>
      </p>
      <% if user_signed_in? %>
        <% if @reply.author_id == current_user.id %>
          <%= link_to "Delete reply", discussion_reply_path(book_id: @reply.discussion.gbook_id, discussion_discussion_id: @reply.discussion_id, reply_id: @reply.id), method: :delete, data: {confirm: 'Are you sure you want to delete this reply?'}, class: "btn btn-danger" %>
          <%= link_to "Edit reply", edit_discussion_reply_path(book_id: @reply.discussion.gbook_id, discussion_discussion_id: @reply.discussion_id, reply_id: @reply.id), class: "btn btn-primary" %>
        <% end %>
      <% end %>
      <%= link_to "View Discussion", discussion_path(book_id: @reply.discussion.gbook_id, discussion_id: @reply.discussion_id), class: "btn btn-primary" %>
      <%= link_to "Back", :back, class: "btn btn-light"%>
    </div>
  </div>
</div>