config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'pages#decide'

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  get 'my_reviews', to: 'review#my_reviews'

  scope 'books', controller: :book do
    scope '/:book_id' do
      resources :reviews, controller: :review, param: :review_id
      resources :discussions, controller: :discussion, param: :discussion_id do
        resources :replies, controller: :reply, param: :reply_id, except: %i[index create update]
      end
      get 'view'
    end

    get 'search'
    get '/:book_id', to: 'book#view'
  end

  get 'search_books', to: 'book#search'
  get 'home', to: 'pages#home'

  resource :replies, controller: :reply, only: %i[create], path: '/books/:book_id/discussions/:discussion_discussion_id/replies',
                     as: 'replies'
  resource :replies, controller: :reply, only: %i[update], path: '/books/:book_id/discussions/:discussion_discussion_id/replies/:reply_id',
                     as: 'reply'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/book_controller.rb
# frozen_string_literal: true

# Book controller
class BookController < ApplicationController
  def view
    # pull the book's info from the google api and turn it into json
    @book_info = HTTP.get("https://www.googleapis.com/books/v1/volumes/#{params[:book_id]}").parse

    # get all the book reviews and calculate the average rating
    @book_reviews = Review.where(gbook_id: params[:book_id])

    if @book_reviews.empty?
      @average_rating = 0
    else
      total = 0

      @book_reviews.each do |book_review|
        total += book_review.rating
      end

      @average_rating = (total.to_f / @book_reviews.size).round(1)
    end
  end

  def search
    @books = search_books(params[:query]) unless params[:query].nil? || params[:query].empty?
  end

  private

  def search_books(query)
    query_string = "https://www.googleapis.com/books/v1/volumes?q=#{query}&maxResults=40".gsub(/\s+/, '%20')
    HTTP.get(query_string).parse['items']
  end
end

app/helpers/book_helper.rb
module BookHelper
end

app/views/book/search.html.erb
<div class="container mt-5">
  <div class="content-section">
    <h1>Search Books</h1>
    <%= form_with url: "/search_books", method: :get do |form| %>
      <div class="mb-3">
        <%= form.text_field :query, placeholder: "Search for something", class: "form-control" %>
      </div>
      <div class="d-grid gap-2 mb-3">
        <%= form.submit "Search", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
  <% unless @books.nil? %>
    <% unless @books.empty? %>
      <% @books.each do |book| %>
        <div class="card mb-3">
          <div class="card-body">
            <p class="card-text">
            <div class="row">
              <div class="col-1">
                <% unless book['volumeInfo']['imageLinks'].nil? %>
                  <% unless book['volumeInfo']['imageLinks']['thumbnail'].nil? %>
                    <%= image_tag book["volumeInfo"]["imageLinks"]["thumbnail"], style: "width: 100%" %>
                  <% end %>
                <% else %>
                  <h5>No image found.</h5>
                <% end %>
              </div>
              <div class="col">
                <h3 class="card-title">
                  <%= book['volumeInfo']['title'] %>
                </h3>
                <h5 class="card-subtitle text-muted mb-2">
                  <% unless book["volumeInfo"]["authors"].nil? %>
                    By: <%= book["volumeInfo"]["authors"].join(', ') %>
                <% else %>
                  No authors found.
                <% end %>
                </h5>
                <%= truncate book['volumeInfo']['description'], length: 500, separator: /\s/ %>
              </div>
            </div>
            </p>
            <%= link_to "View Book", view_path(book_id: book['id']), class: "btn btn-primary" %>
            <%= link_to "Write a Review", new_review_path(book_id: book["id"]), class: "btn btn-primary" %>
            <%= link_to "Read Reviews", reviews_path(book_id: book["id"]), class: "btn btn-primary" %>
          </div>
        </div>
      <% end %>
    <% else %>
    <% end %>
  <% end %>
</div>

app/views/book/view.html.erb
<div class="container mt-5"> 
  <div class="row">
    <div class="col-2">
      <% unless @book_info['volumeInfo']['imageLinks'].nil? %>
        <% unless @book_info['volumeInfo']['imageLinks']['thumbnail'].nil? %>
          <%= image_tag @book_info["volumeInfo"]["imageLinks"]["thumbnail"], style: "width: 100%" %>
        <% end %>
      <% else %>
        <h5>No image found.</h5>
      <% end %>
      <h5 class="mt-3">
        <% if @average_rating == 0 %>
          No ratings yet.
        <% else %>
          Average rating: <%= @average_rating %>/5.0
        <% end %>
      </h5>

    </div>
    <div class="col">
      <h1>
        <%= @book_info["volumeInfo"]["title"] %>
      </h1>
      <h2>
        <% unless @book_info["volumeInfo"]["authors"].nil? %>
          By: <%= @book_info["volumeInfo"]["authors"].join(', ') %>
      <% else %>
        No authors found.
      <% end %>
      </h2>

      <div class="d-grid gap-2 mt-4">
        <%= link_to "Read all reviews for this book", reviews_path(book_id: @book_info["id"]), class: "btn btn-primary" %>
        <%= link_to "Write a review for this book", new_review_path(book_id: @book_info["id"]), class: "btn btn-primary" %>
        <%= link_to "View discussions for this book", discussions_path(book_id: @book_info["id"]), class: "btn btn-primary" %>
        <%= link_to "Start a discussion for this book", new_discussion_path(book_id: @book_info["id"]), class: "btn btn-primary" %>
      </div>
    </div>

    <div class="mt-3">
      <h1 class="mb-3">Recent Reviews</h1>
      <% unless @book_reviews.empty? %>
        <% @book_reviews.first(10).each do |review| %>
          <div class="card mb-3">
            <div class="card-body">
              <div class="d-flex">
                <div>
                  <h3 class="card-title"> 
                    <%= truncate review.title, length: 50, separator: /\s/ %>
                  </h3>
                  <h5 class="card-subtitle mb-2 text-muted">
                    By: <%= review.author.username %></br>
                    Rating: <%= review.rating %>
                  </h5>
                </div>
                <div class="ms-auto">
                  <h5 class="text-muted">
                    <%= review.created_at.strftime("%B %d, %Y at %-I:%M %p") %> 
                  </h5>
                </div>
              </div>
              <p class="card-text">
              <%= truncate review.content, length: 200, separator: /\s/ %>
              </p>
              <%= link_to "View Review", review_path(book_id: review.gbook_id, review_id: review.id), class: "btn btn-primary" %>
            </div>
          </div>
        <% end %>
      <% else %>
        <h2 class="text-center">
          No reviews yet.
        </h2>
      <% end %>
    </div>
  </div>
</div>