config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'pages#decide'

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  get 'my_reviews', to: 'review#my_reviews'

  scope 'books', controller: :book do
    scope '/:book_id' do
      resources :reviews, controller: :review, param: :review_id
      resources :discussions, controller: :discussion, param: :discussion_id do
        resources :replies, controller: :reply, param: :reply_id, except: %i[index create update]
      end
      get 'view'
    end

    get 'search'
    get '/:book_id', to: 'book#view'
  end

  get 'search_books', to: 'book#search'
  get 'home', to: 'pages#home'

  resource :replies, controller: :reply, only: %i[create], path: '/books/:book_id/discussions/:discussion_discussion_id/replies',
                     as: 'replies'
  resource :replies, controller: :reply, only: %i[update], path: '/books/:book_id/discussions/:discussion_discussion_id/replies/:reply_id',
                     as: 'reply'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/discussion.rb
# frozen_string_literal: true

class Discussion < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  has_many :replies, dependent: :destroy

  validates :title, presence: true, length: { minimum: 0, maxmium: 100 }
  validates :content, presence: true, length: { minimum: 0, maxmium: 1000 }
end

app/controllers/discussion_controller.rb
# frozen_string_literal: true

# Discussion controller
class DiscussionController < ApplicationController
  before_action :find_discussion, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]
  before_action :correct_user, only: %i[edit update destroy]

  def index
    @title = 'All Discussions'

    @book_info = HTTP.get("https://www.googleapis.com/books/v1/volumes/#{params[:book_id]}").parse
    @book_name = @book_info['volumeInfo']['title']
    @book_id = params[:book_id]

    # get all the book discussions
    @book_discussions = Discussion.where(gbook_id: @book_id).paginate(page: params[:page], per_page: 10)
  end

  def show
    @title = 'View Discussion'
    @replies = @discussion.replies
  end

  def new
    @discussion = Discussion.new
    @title = 'New Discussion'
    @book_name = (HTTP.get("https://www.googleapis.com/books/v1/volumes/#{params[:book_id]}").parse)['volumeInfo']['title']
  end

  def edit
    @book_name = (HTTP.get("https://www.googleapis.com/books/v1/volumes/#{params[:book_id]}").parse)['volumeInfo']['title']
  end

  def create
    @discussion = Discussion.new(discussion_params)

    @discussion.gbook_id = params[:book_id]
    @discussion.author_id = current_user.id

    book_info = HTTP.get("https://www.googleapis.com/books/v1/volumes/#{params[:book_id]}").parse
    book_name = book_info['volumeInfo']['title']

    @discussion.book_name = book_name

    if @discussion.save
      flash[:notice] = 'Discussion was successfully created.'
      redirect_to discussion_path(book_id: params[:book_id], discussion_id: @discussion.id)
    else
      flash[:alert] = 'Failed to create discussion.'
      redirect_to request.referrer
    end
  end

  def update
    if @discussion.update(discussion_params)
      flash[:notice] = 'Discussion was successfully updated.'
      redirect_to discussion_path(book_id: @discussion.gbook_id, discussion_id: @discussion.id)
    else
      flash[:alert] = 'Failed to update discussion.'
      redirect_to request.referrer
    end
  end

  def destroy
    @discussion.destroy
    flash[:notice] = 'Discussion deleted successfully.'

    redirect_to view_path(book_id: @discussion.gbook_id)
  end

  private

  def find_discussion
    @discussion = Discussion.find(params[:discussion_id])
  end

  def correct_user
    @discussion = current_user.discussions.find(params[:discussion_id])
    redirect_to discussion_path, notice: 'Not authorized to edit this discussion.' if @discussion.nil?
  end

  def discussion_params
    params.require(:discussion).permit(:title, :content)
  end
end

app/helpers/discussion_helper.rb
module DiscussionHelper
end

app/views/discussion/_form.html.erb
<%= form_with model: @discussion do |f| %>
  <div class="mb-3">
    <%= f.label :title, class: "form-label" %>
    <%= f.text_field :title, autocomplete: "title", class: "form-control", required: true, maxlength: 100 %>
  </div>
  <div class="mb-3">
    <%= f.label :content, class: "form-label" %>
    <%= f.text_area :content, autocomplete: "content", class: "form-control", required: true, maxlength: 1000 %>
  </div>
  <div class="mb-3">
    <%= f.submit "Start Discussion", class: "btn btn-primary"%>
  </div>
<% end %>

app/views/discussion/edit.html.erb
<div class="container mt-5">
  <div class="content-section">
    <h2>Edit Discussion</h2>
    <h4 class="text-muted">Book: <%= @book_name %></h4>
    <%= render "form" %>
  </div>
</div>

app/views/discussion/index.html.erb
<div class="container mt-5">
    <div class="d-flex mb-2">
      <div>
        <h1>All Discussions</h1>
        <h5 class="text-muted">Book: <%= @book_name %></h5>
      </div>
      <div class="ms-auto">
        <%= link_to "Start a Discussion", new_discussion_path(book_id: @book_id), class: "btn btn-primary"%>
        <%= link_to "View Book", view_path(book_id: @book_id), class: "btn btn-primary"%>
        <%= link_to "Back", :back, class: "btn btn-light"%>
      </div>
    </div>
  <div class="mt-4">
    <% unless @book_discussions.empty? %>
      <% @book_discussions.each do |discussion| %>
        <div class="card mb-3">
          <div class="card-body">
            <div class="d-flex">
              <div>
                <h3 class="card-title"> 
                  <%= discussion.title %>
                </h3>
                <h5 class="card-subtitle mb-2 text-muted">
                  Started by: <%= discussion.author.username %>
                </h5>
              </div>
              <div class="ms-auto">
                <h5 class="text-muted">
                  <%= discussion.created_at.strftime("%B %d, %Y at %-I:%M %p") %> 
                </h5>
              </div>
            </div>
            <p class="card-text">
            <%= discussion.content %>
            </p>
            <%= link_to "View Discussion", discussion_path(book_id: @book_info["id"], discussion_id: discussion.id), class: "btn btn-primary" %>
          </div>
        </div>
      <% end %>
      <%= will_paginate @book_discussions, list_classes: %w(pagination justify-content-center) %> 
    <% else %>
      <h1 class="text-center">
        No discussions yet.
      </h1>
    <% end %>
  </div>
</div>

app/views/discussion/new.html.erb
<div class="container mt-5">
  <div class="content-section">
    <h2>New Discussion</h2>
    <h4 class="text-muted">Book: <%= @book_name %></h4>
    <%= render "form" %>
  </div>
</div>

app/views/discussion/show.html.erb
<div class= "container mt-5">
  <div class="card mb-3">
    <div class="card-body">
      <h1 class="card-title"> 
        <%= @discussion.title %>
      </h1>
      <h5 class="card-subtitle mb-3 text-muted">
        <b>Written by:</b> <%= @discussion.author.username %></br>
        <b>Written on:</b> <%= @discussion.created_at.strftime("%B %d, %Y at %-I:%M %p") %> 
      </h5>
      <p class="card-text">
      <%= @discussion.content %>
      </p>
      <% if user_signed_in? %>
        <% if @discussion.author_id == current_user.id %>
          <%= link_to "Delete discussion", discussion_path(book_id: @discussion.gbook_id, discussion_id: @discussion.id), method: :delete, data: {confirm: 'Are you sure you want to delete this discussion?'}, class: "btn btn-danger" %>
          <%= link_to "Edit discussion", edit_discussion_path(book_id: @discussion.gbook_id, discussion_id: @discussion.id), class: "btn btn-primary" %>
        <% end %>
      <% end %>
      <%= link_to "View Book", view_path(book_id: @discussion.gbook_id), class: "btn btn-primary" %>
      <%= link_to "Write a Reply", new_discussion_reply_path(discussion_discussion_id: @discussion.id), class: "btn btn-primary" %>
      <%= link_to "Back", :back, class: "btn btn-light"%>
    </div>
  </div>

  <% unless @replies.nil? %>
    <% unless @replies.empty? %>
      <div class="row justify-content-end">
        <div class="col-11">
          <% @replies.each do |reply| %>
            <div class="card mb-3">
              <div class="card-body">
                <div class="d-flex mb-2">
                  <div>
                    <h6 class="card-subtitle text-muted"><%= reply.author.username %> on <%= reply.created_at.strftime("%B %d, %Y at %-I:%M %p") %></h6>
                  </div>
                  <div class="ms-auto">
                    <%= link_to "View Reply", discussion_reply_path(book_id: reply.discussion.gbook_id, discussion_discussion_id: reply.discussion_id, reply_id: reply.id), class: "btn btn-primary" %>
                  </div>
                </div>
                <p class="card-text"><%= reply.content %></p>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>