config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'pages#decide'

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  get 'my_reviews', to: 'review#my_reviews'

  scope 'books', controller: :book do
    scope '/:book_id' do
      resources :reviews, controller: :review, param: :review_id
      resources :discussions, controller: :discussion, param: :discussion_id do
        resources :replies, controller: :reply, param: :reply_id, except: %i[index create update]
      end
      get 'view'
    end

    get 'search'
    get '/:book_id', to: 'book#view'
  end

  get 'search_books', to: 'book#search'
  get 'home', to: 'pages#home'

  resource :replies, controller: :reply, only: %i[create], path: '/books/:book_id/discussions/:discussion_discussion_id/replies',
                     as: 'replies'
  resource :replies, controller: :reply, only: %i[update], path: '/books/:book_id/discussions/:discussion_discussion_id/replies/:reply_id',
                     as: 'reply'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/pages/home.html.erb
<div class="container mt-5">
  <h1 class="mb-3">Welcome, <%= current_user.username %>!</h1>

  <% unless @user_reviews.empty? %>
    <div class="d-flex">
      <div>
        <h3 class="mt-1 mb-3">Your Recent Reviews</h3>
      </div>
      <div class="ms-auto">
        <%= link_to "View All", my_reviews_path, class: "btn btn-primary" %>
      </div>
    </div>
    <% @user_reviews.each do |review| %>
      <div class="card mb-3">
        <div class="card-body">
          <div class="d-flex">
            <div>
              <h3 class="card-title"> 
                <%= review.title %>
              </h3>
            </div>
            <div class="ms-auto">
              <h5 class="text-muted">
                <%= review.created_at.strftime("%B %d, %Y at %-I:%M %p") %>
              </h5>
            </div>
          </div>
          <h5 class="card-subtitle mb-2 text-muted">
            Book: <%= review.book_name %></br>
            Rating: <%= review.rating %>
          </h5>
          <p class="card-text">
          <%= truncate review.content, length: 500, separator: /\s/ %>
          </p>
          <%= link_to "View Review", review_path(book_id: review.gbook_id, review_id: review.id), class: "btn btn-primary" %>
          <%= link_to "View Book", view_path(book_id: review.gbook_id), class: "btn btn-primary" %>
        </div>
      </div>
    <% end %>
  <% else %>
    <div class="mt-5">
      <h3 class="text-center">
        You don't have any reviews yet.
      </h3>
      <h5 class="text-center text-muted">
        Click on the 'Search Books' button in the navbar to get started.
      </h5>
    </div>
  <% end %>

</div>